sources:
  - name: votes-goerli
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/9032/votes-goerli/version/latest
documents:
  - "./src/graphclient-queries/**/*.{gql,graphql}"