sources:
  - name: votes-goerli
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/9032/votes-goerli/version/latest
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
documents:
  - "./schema/graphclient-queries/**/*.{gql,graphql}"