query GetAuction($id: ID!) {
  auction(id: $id) {
    id
    amount
    bidder
    startTime
    endTime
    settled
    extended
    vote {
      id
      owner
      tokenId
      uri
    }
    contract {
      id
      treasury
      duration
      timeBuffer
      minBidIncrement
      launched
      reservePrice
      reserveAddress
      raffleAddress
      votesURI
      flashVotesURI
      paused
      votesToken
    }
  }
}