query GetAuctionContract($id: ID!) {
  auctionContract(id: $id) {
    id
    treasury
    duration
    timeBuffer
    minBidIncrement
    launched
    reservePrice
    reserveAddress
    raffleAddress
    votesURI
    flashVotesURI
    paused
    votesToken
  }
}
