query GetAuctions($first: Int, $orderBy: Auction_orderBy, $orderDirection: OrderDirection, $where: Auction_filter){
  auctions(first: $first, orderBy: $orderBy, orderDirection: $orderDirection, where: $where) {
    id
    startTime
    endTime
    amount
    bidder
    extended
    settled
    tokenId
    vote {
      id
      owner
      tokenId
      uri
    }
    contract {
      id
      treasury
      duration
      timeBuffer
      minBidIncrement
      launched
      reservePrice
      reserveAddress
      raffleAddress
      votesURI
      flashVotesURI
      paused
      votesToken
    }
  }
}