query GetAuctionSettleds($first: Int, $orderBy: AuctionSettled_orderBy, $orderDirection: OrderDirection) {
  auctionSettleds(first: $first, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    winner
    tokenId
    amount
  }
}