query GetQuestions($first: Int, $orderBy: Question_orderBy, $orderDirection: OrderDirection, $where: Question_filter){
  questions(first: $first, orderBy: $orderBy, orderDirection: $orderDirection, where: $where) {
    id
    asker
    question
    vote {
      id
    }
    state
    modifiedTimestamp
    contract {
      id
    }
  }
}