query GetVote($id: ID!) {
  vote(id: $id) {
    id
    owner
    tokenId
    uri
    auction {
      id
      tokenId
      amount
      bidder
      startTime
      endTime
      settled
      extended
    }
  }
}