query GetVote($id: ID!) {
  vote(id: $id) {
    id
    owner
    tokenId
    uri
    contract {
      id
    }
    auction {
      id
      tokenId
      amount
      bidder
      startTime
      endTime
      settled
      extended
      contract {
        id
      }
    }
  }
}