// @generated
// This file is autogenerated, do not edit manually

module Main = {
  module Route = Route__Main_route

  module Auction = {
    module Route = Route__Main__Auction_route

    module Bids = {
      module Route = Route__Main__Auction__Bids_route

    }
  }
  module Queue = {
    module Route = Route__Main__Queue_route

  }
  module Raffles = {
    module Route = Route__Main__Raffles_route

  }
  module Votes = {
    module Route = Route__Main__Votes_route

  }
  module Questions = {
    module Route = Route__Main__Questions_route

  }
}
module FourOhFour = {
  module Route = Route__FourOhFour_route

}