// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphqlYoga from "graphql-yoga";
import * as GatewayMjs from "../src/schema/gateway.mjs";

function makeGatewaySchema(prim) {
  return GatewayMjs.makeGatewaySchema();
}

var $$default = GraphqlYoga.createYoga({
      schema: GatewayMjs.makeGatewaySchema(),
      context: (async function (param) {
          
        }),
      graphqlEndpoint: "/api/graphql"
    });

export {
  makeGatewaySchema ,
  $$default as default,
}
/* default Not a pure module */
